export enum YAD2_ASSET {
  APARTMENT = 'דירה',
  GARDEN_APARTMENT = 'דירת גן',
  PRIVATE_HOUSE_OR_COTTEGE = 'בית פרטי/קוטג׳',
  ROOF_OR_PENTHOUSE = 'גג/פנתהאוס',
  LOT = 'מגרשים',
  DUPLEX = 'דופלקס',
  VACATION_APARTMENT = 'דירת נופש',
  TOWNHOUSE = 'דו משפחתי',
  BASEMENT = 'מרתף/פרטר',
  TRIPLEX = 'טריפלקס',
  UNIT = 'יחידת דיור',
  AGRICULTURAL_FARM = 'משק חקלאי',
  AUXILIARY_FARM = 'משק עזר',
  ASSISTED_LIVING = 'דיור מוגן',
  BUILDING = 'בניין מגורים',
  STUDIO = 'סטודיו/לופט',
  STORAGE = 'מחסן',
  PARKING = 'חניה',
  PURCHASING_GROUP = 'קבוצת רכישה/זכות לנכס',
  GENERAL = 'כללי',
}

